#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.bash

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXX)

cat > $payload <&0

start_docker

repository="$(jq -r '.source.repository // ""' < $payload)"
tag="$(jq -r '.source.tag // "latest"' < $payload)"

docker pull "${repository}:${tag}"

image=$(docker_image "$repository" "$tag")
if [ -z "$image" ]; then
  echo "failed to determine image id :("
  exit 1
fi

mkdir -p $destination
docker save -o ${destination}/image "$image"
echo "$repository" > ${destination}/repository
echo "$tag" > ${destination}/tag
echo "$image" > ${destination}/image-id

jq -n "{
  version: {
    image: $(echo $image | jq -R .)
  }
}" >&3
