#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.bash

source=$1

if [ -z "$source" ]; then
  echo "usage: $0 <path/to/source>"
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/resource-in.XXXXX)

cat > $payload <&0

cd $(dirname $source)

start_docker

username=$(jq -r '.params.username // ""' < $payload)
password=$(jq -r '.params.password // ""' < $payload)
email=$(jq -r '.params.email // ""' < $payload)

if [ -z "$username" ] || [ -z "$password" ] || [ -z "$email" ]; then
  echo "must specify username, password, and email params"
  exit 1
fi

docker login -u "$username" -p "$password" -e "$email"

build=$(jq -r '.params.build // ""' < $payload)

load=$(jq -r '.params.load // ""' < $payload)

load_file=$(jq -r '.params.load_file // ""' < $payload)
load_repository=$(jq -r '.params.load_repository // ""' < $payload)
load_tag=$(jq -r '.params.load_tag // "latest"' < $payload)

pull_repository=$(jq -r '.params.pull_repository // ""' < $payload)
pull_tag=$(jq -r '.params.pull_tag // "latest"' < $payload)

repository=$(jq -r '.params.repository // ""' < $payload)
tag=$(jq -r '.params.tag // "latest"' < $payload)

if [ -n "$build" ]; then
  docker build -t "${repository}:${tag}" "$build"
elif [ -n "$load" ]; then
  docker load -i "${load}/image"
  docker tag "$(cat ${load}/image-id)" "${repository}:${tag}"
elif [ -n "$load_file" ]; then
  docker load -i $load_file
  docker tag "${load_repository}:${load_tag}" "${repository}:${tag}"
elif [ -n "$pull_repository" ]; then
  docker pull "${pull_repository}:${pull_tag}"
  docker tag "${pull_repository}:${pull_tag}" "${repository}:${tag}"
else
  echo "must specify build or image param"
  exit 1
fi

docker push "${repository}:${tag}"

jq -n "{
  version: {
    image: $(docker_image "$repository" "$tag" | jq -R .)
  }
}" >&3
