#!/bin/bash

set -eux

ginkgo -race -r cmd/
GOOS=linux ginkgo build -r tests/
docker run -it --privileged -v `pwd`:/docker-image-resource concourse/buildroot:iptables /docker-image-resource/tests/tests.test