---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
- name: docker-image-resource
  path: gopath/src/github.com/concourse/docker-image-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/concourse/docker-image-resource/ci/scripts/build
